package codigo;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import jdk.nashorn.internal.ir.CatchNode;

/**
 *
 * @author Rocio Soriano
 * 
 * 
 * 
 * //requisitos pokedex: 
 */
public class VentanaPokedex extends javax.swing.JFrame {

    BufferedImage buffer1 = null;
    Image imagen1 = null;
    int contador = 0;
Image fondo;  
    //variables para conectar BBDD
    Statement estado;
    ResultSet resultadoConsulta;
    Connection conexion;
   

    @Override
    public void paint(Graphics g) {
        super.paintComponents(g);
        Graphics2D g2 = (Graphics2D) imagenPokemon.getGraphics();
        g2.drawImage(buffer1, 0, 0, imagenPokemon.getWidth(), imagenPokemon.getHeight(), null);
     
    }

    /**
     * Creates new form VentanaPokedex
     */
    public VentanaPokedex() {
        initComponents();
        
        try {
            imagen1 = ImageIO.read(getClass().getResource("/imagenes/black-white.png"));
        } catch (IOException ex) {

        }
        buffer1 = (BufferedImage) imagenPokemon.createImage(imagenPokemon.getWidth(), imagenPokemon.getHeight());
        Graphics2D g2 = buffer1.createGraphics();
        dibujaElPokemonQueEstaEnLaPosicion(30);

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conexion
                    = DriverManager.getConnection("jdbc:mysql://192.168.126.128/pokedex", "root", "");
            estado = conexion.createStatement();

        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("NO SE OYE!!! NO SE OYE!!");
        }

    }

    private void dibujaElPokemonQueEstaEnLaPosicion(int posicion) {
        int fila = posicion / 31;
        int columna = posicion % 31;
        Graphics2D g2 = (Graphics2D) buffer1.getGraphics();
        g2.setColor(Color.black);
        g2.fillRect(0, 0, imagenPokemon.getWidth(), imagenPokemon.getHeight());
        //posicion X denro del jPanell
        g2.drawImage(imagen1, 0,//posicion X dentro del jPanell
                0,//posicion Y dentro del jPanell
                imagenPokemon.getWidth(),//ancho JPanel
                imagenPokemon.getHeight(),//alto JPanel
                columna * 96,//posicion inicial X dentro de la imagen
                fila * 96,//posicion inicial X dentro de la imagen
                columna * 96 + 96,//posicion final X
                fila * 96 + 96,//posicion final Y
                null);//si no lo pones no va
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        der = new javax.swing.JButton();
        nombrePokemon = new javax.swing.JLabel();
        imagenPokemon = new javax.swing.JPanel();
        izq = new javax.swing.JButton();
        peso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pokedexInterfaz = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        der.setText(">");
        der.setAutoscrolls(true);
        der.setBorderPainted(false);
        der.setContentAreaFilled(false);
        der.setDoubleBuffered(true);
        der.setFocusPainted(false);
        der.setFocusable(false);
        der.setVerifyInputWhenFocusTarget(false);
        der.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derActionPerformed(evt);
            }
        });
        getContentPane().add(der, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 40, 30));

        nombrePokemon.setBackground(new java.awt.Color(102, 255, 102));
        nombrePokemon.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        nombrePokemon.setForeground(new java.awt.Color(204, 255, 51));
        nombrePokemon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nombrePokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 330, 40));

        javax.swing.GroupLayout imagenPokemonLayout = new javax.swing.GroupLayout(imagenPokemon);
        imagenPokemon.setLayout(imagenPokemonLayout);
        imagenPokemonLayout.setHorizontalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        imagenPokemonLayout.setVerticalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        getContentPane().add(imagenPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 210, 190));

        izq.setForeground(new java.awt.Color(0, 51, 0));
        izq.setText("<");
        izq.setAutoscrolls(true);
        izq.setBorderPainted(false);
        izq.setContentAreaFilled(false);
        izq.setDefaultCapable(false);
        izq.setDoubleBuffered(true);
        izq.setFocusPainted(false);
        izq.setFocusable(false);
        izq.setRequestFocusEnabled(false);
        izq.setRolloverEnabled(false);
        izq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izqActionPerformed(evt);
            }
        });
        getContentPane().add(izq, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 40, 30));

        peso.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        peso.setForeground(new java.awt.Color(255, 255, 102));
        getContentPane().add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 160, 30));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 290, 180));

        pokedexInterfaz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pokedexInterfaz.setForeground(new java.awt.Color(255, 255, 51));
        pokedexInterfaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(pokedexInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -50, 780, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void derActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derActionPerformed

        dibujaElPokemonQueEstaEnLaPosicion(contador);
        try {
            resultadoConsulta = estado.executeQuery("SELECT * FROM `pokemon` WHERE `id` =" + (contador+1));
            if (resultadoConsulta.next()){
                nombrePokemon.setText(resultadoConsulta.getString(2));//el numero es la columna
                
                peso.setText(resultadoConsulta.getString(4));//el numero es la columna
            
            }else{
                nombrePokemon.setText("Pokemon extinto");
                pokedexInterfaz.setText("Sin ganas de saberlo");
            }
        } catch (SQLException ex) {
            System.out.println("mierda pa ti");
            

        }contador++;
        if (contador >= 649) {
            contador = 649;
        }
    }//GEN-LAST:event_derActionPerformed

    private void izqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izqActionPerformed
        dibujaElPokemonQueEstaEnLaPosicion(contador);

        try {
            resultadoConsulta = estado.executeQuery("SELECT * FROM `pokemon` WHERE `id` =" + (contador+1));
            if (resultadoConsulta.next()){
                nombrePokemon.setText(resultadoConsulta.getString(2));
                peso.setText(resultadoConsulta.getString(4));//el numero es la columna

            }else{
                nombrePokemon.setText("Pokemon extinto");
            }
        } catch (SQLException ex) {

        }contador--;

        if (contador <= 0) {
            contador = 1;
        }
    }//GEN-LAST:event_izqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPokedex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton der;
    private javax.swing.JPanel imagenPokemon;
    private javax.swing.JButton izq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombrePokemon;
    private javax.swing.JLabel peso;
    private javax.swing.JLabel pokedexInterfaz;
    // End of variables declaration//GEN-END:variables
}
