package codigo;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author Rocio Soriano
 *
 *
 *
 * //requisitos pokedex:
 */
public class VentanaPokedex extends javax.swing.JFrame {

    BufferedImage buffer1 = null;
    Image imagen1 = null;
    int contador = 0;
    Image fondo;
    //variables para conectar BBDD
    Statement estado;
    ResultSet resultadoConsulta;
    Connection conexion;
    Clip musica;
    
    //vamos a declarar el Hashmap : estructura pàra guardar todo el contenido de la base de datos de golpe
    
    HashMap <String, Pokemon> listaPokemons = new HashMap(); //esto solo guarda strings de pokemon

    @Override
    public void paint(Graphics g) {
        super.paintComponents(g);
        Graphics2D g2 = (Graphics2D) imagenPokemon.getGraphics();
        g2.drawImage(buffer1, 0, 0, imagenPokemon.getWidth(), imagenPokemon.getHeight(), null);

    }

    /**
     * Creates new form VentanaPokedex
     */
    public VentanaPokedex() {
        initComponents();

        try {
            imagen1 = ImageIO.read(getClass().getResource("/imagenes/black-white.png"));
        } catch (IOException ex) {

        }
        buffer1 = (BufferedImage) imagenPokemon.createImage(imagenPokemon.getWidth(), imagenPokemon.getHeight());
        Graphics2D g2 = buffer1.createGraphics();
        dibujaElPokemonQueEstaEnLaPosicion(0);

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conexion
                    = DriverManager.getConnection("jdbc:mysql://192.168.126.130/pokedex", "root", "");
            estado = conexion.createStatement();
            
            
            //hasmhmap:
            
           resultadoConsulta = estado.executeQuery("Select * from pokemon");
           //recorremos el array del resultado uno a uno para ir cargandolo en el Hashmap
           while (resultadoConsulta.next()){
           Pokemon p = new Pokemon(); //por cada pokemon que recorremos se genera un objeto p
           p.nombre = resultadoConsulta.getString("nombre");
           p.peso = resultadoConsulta.getString("peso");
           p.especie = resultadoConsulta.getString("especie");
           p.movimiento1 = resultadoConsulta.getString("movimiento1");
           p.movimiento2 = resultadoConsulta.getString("movimiento2");
           p.movimiento3 = resultadoConsulta.getString("movimiento3");
           p.habilidad = resultadoConsulta.getString("habilidad");
           p.altura = resultadoConsulta.getString("altura");
           p.tipo1 = resultadoConsulta.getString("tipo1");
           p.tipo2 = resultadoConsulta.getString("tipo2");
           p.descripcion = resultadoConsulta.getString("descripcion");
            p.habitat = resultadoConsulta.getString("habitat");
             p.id = resultadoConsulta.getString("id");
        
           //añado el pokemon
           listaPokemons.put(resultadoConsulta.getString("id"), p);
            
           }

        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("NO SE OYE!!! NO SE OYE!!");
        }

    }

    private void dibujaElPokemonQueEstaEnLaPosicion(int posicion) {
        int fila = posicion / 31;
        int columna = posicion % 31;
        Graphics2D g2 = (Graphics2D) buffer1.getGraphics();
        g2.setColor(Color.black);
        g2.fillRect(0, 0, imagenPokemon.getWidth(), imagenPokemon.getHeight());
        //posicion X denro del jPanell
        g2.drawImage(imagen1, 0,//posicion X dentro del jPanell
                0,//posicion Y dentro del jPanell
                imagenPokemon.getWidth(),//ancho JPanel
                imagenPokemon.getHeight(),//alto JPanel
                columna * 96,//posicion inicial X dentro de la imagen
                fila * 96,//posicion inicial X dentro de la imagen
                columna * 96 + 96,//posicion final X
                fila * 96 + 96,//posicion final Y
                null);//si no lo pones no va
        repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        der = new javax.swing.JButton();
        nombrePokemon = new javax.swing.JLabel();
        imagenPokemon = new javax.swing.JPanel();
        izq = new javax.swing.JButton();
        peso = new javax.swing.JLabel();
        altura = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        especie = new javax.swing.JLabel();
        habitat = new javax.swing.JLabel();
        tipos = new javax.swing.JLabel();
        habilidad = new javax.swing.JLabel();
        movimiento = new javax.swing.JLabel();
        tipo2 = new javax.swing.JLabel();
        mov2 = new javax.swing.JLabel();
        mov3 = new javax.swing.JLabel();
        descripcion1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        pokedexInterfaz = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        der.setText(">");
        der.setAutoscrolls(true);
        der.setBorderPainted(false);
        der.setContentAreaFilled(false);
        der.setDoubleBuffered(true);
        der.setFocusPainted(false);
        der.setFocusable(false);
        der.setVerifyInputWhenFocusTarget(false);
        der.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derActionPerformed(evt);
            }
        });
        getContentPane().add(der, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 40, 30));

        nombrePokemon.setBackground(new java.awt.Color(102, 255, 102));
        nombrePokemon.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        nombrePokemon.setForeground(new java.awt.Color(204, 255, 51));
        nombrePokemon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nombrePokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 330, 30));

        javax.swing.GroupLayout imagenPokemonLayout = new javax.swing.GroupLayout(imagenPokemon);
        imagenPokemon.setLayout(imagenPokemonLayout);
        imagenPokemonLayout.setHorizontalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        imagenPokemonLayout.setVerticalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        getContentPane().add(imagenPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 210, 190));

        izq.setForeground(new java.awt.Color(0, 51, 0));
        izq.setText("<");
        izq.setAutoscrolls(true);
        izq.setBorderPainted(false);
        izq.setContentAreaFilled(false);
        izq.setDefaultCapable(false);
        izq.setDoubleBuffered(true);
        izq.setFocusPainted(false);
        izq.setFocusable(false);
        izq.setRequestFocusEnabled(false);
        izq.setRolloverEnabled(false);
        izq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izqActionPerformed(evt);
            }
        });
        getContentPane().add(izq, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 40, 30));

        peso.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        peso.setForeground(new java.awt.Color(255, 255, 102));
        getContentPane().add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 160, 40));

        altura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        altura.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 160, 40));

        numero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numero.setForeground(new java.awt.Color(255, 255, 102));
        getContentPane().add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 90, 30));

        especie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        especie.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(especie, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 300, 40));

        habitat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        habitat.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(habitat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 330, 30));

        tipos.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tipos.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(tipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 150, 30));

        habilidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        habilidad.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(habilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 330, 30));

        movimiento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        movimiento.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(movimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 100, 40));

        tipo2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tipo2.setForeground(new java.awt.Color(255, 255, 102));
        getContentPane().add(tipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 160, 30));

        mov2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mov2.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(mov2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 100, 40));

        mov3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mov3.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(mov3, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 460, 120, 40));

        descripcion1.setForeground(new java.awt.Color(255, 255, 0));
        descripcion1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        descripcion1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        descripcion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        descripcion.setBackground(new java.awt.Color(0, 0, 0));
        descripcion.setColumns(20);
        descripcion.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        descripcion.setForeground(new java.awt.Color(255, 255, 0));
        descripcion.setRows(5);
        descripcion1.setViewportView(descripcion);

        getContentPane().add(descripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 300, 180));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        pokedexInterfaz.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        pokedexInterfaz.setForeground(new java.awt.Color(255, 255, 51));
        pokedexInterfaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(pokedexInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 780, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void derActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derActionPerformed
        dibujaElPokemonQueEstaEnLaPosicion(contador);

        Pokemon p = listaPokemons.get(String.valueOf(contador + 1));
        if (p != null) {
            nombrePokemon.setText(p.nombre);
            peso.setText(p.peso);
           altura.setText(p.altura);
            numero.setText(p.id);
           habilidad.setText(p.habilidad);
           especie.setText(p.especie);
           habitat.setText(p.habitat);
           tipos.setText("tipos:  " + p.tipo1);
           tipo2.setText(p.tipo2);
           descripcion.setLineWrap(true);
            descripcion.setText(p.descripcion);
            movimiento.setText(p.movimiento1);
           mov2.setText(p.movimiento2);
           mov3.setText(p.movimiento3);
          
           
          
           
            
        } else {
            nombrePokemon.setText("FALLO!!!!");
            tipo2.setText("no tiene mas!");
        }
        contador++;
        if (contador >= 649) {
            contador = 649;
        }


    }//GEN-LAST:event_derActionPerformed

    private void izqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izqActionPerformed
        dibujaElPokemonQueEstaEnLaPosicion(contador);

        Pokemon p = listaPokemons.get(String.valueOf(contador + 1));
        if (p != null) {
            nombrePokemon.setText(p.nombre);
            especie.setText(p.especie);
            peso.setText(p.peso);
            altura.setText(p.altura);
            numero.setText(p.id);
            habilidad.setText(p.habilidad);
            especie.setText(p.especie);
            habitat.setText(p.habitat);
            descripcion.setLineWrap(true);
            descripcion.setText(p.descripcion);
            movimiento.setText(p.movimiento1);
            mov2.setText(p.movimiento2);
            mov3.setText(p.movimiento3);
        } else {
            nombrePokemon.setText("FALLO!!!!");
            tipo2.setText("no tiene mas!");
        }

        contador--;

        if (contador <= 0) {
            contador = 1;
        }
  
    }//GEN-LAST:event_izqActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           try {
            musica = AudioSystem.getClip();
            musica.open(AudioSystem.getAudioInputStream(getClass().getResource("/sonidos/musica.wav")));
        } catch (LineUnavailableException ex) {
            
        } catch (UnsupportedAudioFileException ex) {
               
        } catch (IOException ex) {
         
        }
  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPokedex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altura;
    private javax.swing.JButton der;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JScrollPane descripcion1;
    private javax.swing.JLabel especie;
    private javax.swing.JLabel habilidad;
    private javax.swing.JLabel habitat;
    private javax.swing.JPanel imagenPokemon;
    private javax.swing.JButton izq;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel mov2;
    private javax.swing.JLabel mov3;
    private javax.swing.JLabel movimiento;
    private javax.swing.JLabel nombrePokemon;
    private javax.swing.JLabel numero;
    private javax.swing.JLabel peso;
    private javax.swing.JLabel pokedexInterfaz;
    private javax.swing.JLabel tipo2;
    private javax.swing.JLabel tipos;
    // End of variables declaration//GEN-END:variables
}
